### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by joshcummingsdesign** [kurtsson/jekyll-multiple-languages-plugin#128]
AppVeyor is misconfigured and is failing builds with the following error:

```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

We should either fix AppVeyor or use CircleCI or the like.

**Comment by shushugah** [comment]
Plusone, happy to implement TravisCI.com, unless there are strong preferences for something else.

**Comment by kurtsson** [comment]
@shushugah I added the Travis integration and a minimal .travis.yml conf. It needs some love however but I leave that to you :)
https://travis-ci.com/kurtsson/jekyll-multiple-languages-plugin

**Comment by kurtsson** [comment]
Fixed
