### ISSUE TITLE
 Liquid Exception: Liquid syntax error (line 17): Unknown tag 't'

### ISSUE THREAD

**Issue by fifou17** [kurtsson/jekyll-multiple-languages-plugin#142]
i have installed the plugin in my site and created folder _18n and added en.yml and included the {% t global.english %} its doesnt recognize the t tag in jekyll 3.8.5

**Comment by fifou17** [comment]
nvm its works i used bundle install --force

**Comment by pbatard** [comment]
For those who come to this issue and find that `bundle install --force` does not help, another thing you want to make sure is that you added the `gem "jekyll-multiple-languages-plugin"` line inside the following section in your `Gemfile`:
```
group :jekyll_plugins do
  (...)
end
```

For instance, this will work as expected:

```
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-multiple-languages-plugin"
end
```

Whereas this will produce the dreaded `Liquid syntax error (line ##): Unknown tag 't'`:

```
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

gem "jekyll-multiple-languages-plugin"
```

At least, that's what did the trick for me...
