### ISSUE TITLE
Jekyll 4.0 compatibility

### ISSUE THREAD

**Issue by kleuter** [kurtsson/jekyll-multiple-languages-plugin#149]
Would love to update to Jekyll 4 but this awesome plugin still keeps me on 3.8.6 😢 

``
Dependency Error: Yikes! It looks like you don't have jekyll-multiple-languages-plugin or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-multiple-languages-plugin gem in your Gemfile as well. The full error message from Ruby is: 'Unable to activate jekyll-multiple-languages-plugin-1.6.0, because jekyll-4.0.0 conflicts with jekyll (>= 2.0, < 4.0)' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
``

**Comment by shushugah** [comment]
I have two initial thoughts

1. Asides from increasing the ceiling requirement for the gem, is there anything else that needs to change? For example `<a href="{{ site.baseurl_root }}/{{ lang }}{{ page.url }}" >{% t langs.{{ lang }} %}</a>` will become `<a href="{{ lang }}{{ page.url }}" >{% t langs.{{ lang }} %}</a>` or possibly breaks, we need to investigate this. 

2. Any idea whether Jekyll 4 itself will have I18n support natively?

**Comment by shushugah** [comment]
I loosened the requirements and it just works, let me know if you find any bugs! #151

**Comment by rudygodoy** [comment]
Any chance this is merged and released sometime soon?

**Comment by kurtsson** [comment]
This is fixed in the latest release
