### ISSUE TITLE
Not translating in frontmatter

### ISSUE THREAD

**Issue by NebelNidas** [kurtsson/jekyll-multiple-languages-plugin#160]
When I have something like `title: about.title` in my frontmatter, as described like [here](https://github.com/kurtsson/jekyll-multiple-languages-plugin#54-i18n-in-templates), it doesn't take the actual string from my translation file (as expected), it just returns back "about.title".

```
_i18n
├── de/
└── de.yml
└── en.yml
```

de.yml:
```
about:
  title: Über
```
en.yml:
```
about:
  title: About
```

**Comment by TimSeryakov** [comment]
I am also looking for a solution to this issue

**Comment by NebelNidas** [comment]
Wow, thanks! I can't believe I've missed this line... 🤦‍♂️
