### ISSUE TITLE
Are GitHub Pages not supported?

### ISSUE THREAD

**Issue by gilgongo** [kurtsson/jekyll-multiple-languages-plugin#180]
Hi - I'm getting "The tag tf is not a recognized Liquid tag"  when I try to deploy to GitHub Pages using 1.7.0.

Is this a known issue?

**Comment by shushugah** [comment]
Yup, Github Pages runs jekyll in safe mode, which excludes 3rd party jekyll plugins including this one. You could either run the jekyll code locally/in a CI, and upload the raw html to githubpages, or uses a separate service like gitlab or netlify to run jekyll with 3rd party plugins. See this for some more context https://github.com/jekyll/jekyll/issues/5265
