### ISSUE TITLE
Translate and filter not possible

### ISSUE THREAD

**Issue by sedrubal** [kurtsson/jekyll-multiple-languages-plugin#181]
For the RSS feed I need to pipe the translated string through `|xml_escape`. Before using jekyll-multiple-languages-plugin, I had this:

```html
<title>{{ post.title | xml_escape }}</title>
```

Now I'm searching for a solution like:

```html
<title>{% t post.title | xml_escape %}</title>
```

But this results in an empty string.

**Comment by shushugah** [comment]
would this work?

```
{% assign post_title = t post.title %}
<title>{% post_title | xml_escape %}</title>
```

**Comment by sedrubal** [comment]
> would this work?
> 
> ```
> {% assign post_title = t post.title %}
> <title>{% post_title | xml_escape %}</title>
> ```

No this does not work, neither. It's still empty.

**Comment by shushugah** [comment]
My bad, it should be 

```
{% assign post_title = t post.title %}
<title>{{ post_title | xml_escape }}</title>
```

and can you confirm that 
`{% t post.title %}` is not empty in first place?

**Comment by sedrubal** [comment]
This does not work neither.

I have:

```html
<title>{%- t post.title -%}</title>
```

which prints the title but without `xml_espace`.

```html
{% assign post_title = t post.title %}
{{ post_title }}
```

This does print nothing. It seems, `t` does not work with `assign`. Thus

```
{% assign post_title = t post.title %}
<title>{{ post_title | xml_escape }}</title>
```

Is empty, too.

**Comment by shushugah** [comment]
this for sure would work tho, and seems to be issue...with chaining liquid filters, something I admittedly don't understand very well

```liquid
{% capture yolo %}{% t post.title %}{% endcapture %}
<title>{{ yolo | | xml_escape }}</title>
```

**Comment by sedrubal** [comment]
Thank you, this works for me.
