### ISSUE TITLE
Reference image in page template

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [kurtsson/jekyll-multiple-languages-plugin#192]
I have the about template:

```
---
layout: page
title: About
permalink: /about/
image: '{{site.baseurl_root}}/images/60.jpg'
---

{% translate_file _pages/about.md %}
```

I tried:

```
image: '{{site.baseurl_root}}/images/60.jpg'
```

and

```
image: '/images/60.jpg'
```

It doesn't work for me, I am trying to avoid duplicate images, with

```
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]
```

**Comment by favarete** [comment]
What's the resulting URL from the `{{site.baseurl_root}}/images/60.jpg`? Does this URL make sense to you accordingly with the value on `baseurl` from your `_config.yml`? It's working on the default language at least or isn't working at all?

**Comment by JavierSegoviaCordoba** [comment]
The problem was on the HTML or javascript side, sorry, I am new in web development so I haven't define there the URL.
