### ISSUE TITLE
this plugin doesn't work [octopress]

### ISSUE THREAD

**Issue by eguneys** [kurtsson/jekyll-multiple-languages-plugin#23]
This is my folder structure

```
.
|-- en
|   `-- _posts
|       |-- a.md
|       |-- b.md
|       |-- c.md
|       `-- d.md
|-- en.yml
|-- tr
|   `-- _posts
|       `-- t.md
`-- tr.yml
```

this is my `index.html`

```
{% assign post = site.posts.first %}
<article class="hentry">
  {% include article.html %}
</article><!-- /.hentry -->
```

The problem is when I visit http://localhost/tr, I can't see the `t.md` but the posts in `en` folder `a.md b.md c.md`. What is wrong?

You can see my repo at [github](https://github.com/eguneys/eguneys.github.io/tree/gh-pages/source), note that it's on `gh-pages` branch.

Please fix it asap.

**Comment by Anthony-Gaudino** [comment]
@eguneys this is a very old issue and I don't believe you are interested in it anymore.

If you are still interested, please try using the newest plugin version, maybe it can solve your problem.
