### ISSUE TITLE
Content sharing among languages

### ISSUE THREAD

**Issue by JulianJorgensen** [kurtsson/jekyll-multiple-languages-plugin#30]
Great plugin!! Thank you!

I have 3 languages. 2 of them are almost identical except for a few variables in the language.yml file. Currently I solve this problem by simply using the Jekyll "include" to share the content. This works for all content files, but not for the YML files.

Is there a better way to share content among languages?
Is it possible to merge 2 yaml files? Or somehow "include" yaml content from another yaml file?

Does this all make sense? All I want to do is keep my code simple and not repeat any content. It means a lot to me :)

Thanks guys!

**Comment by kurtsson** [comment]
I'm not sure what you want here. Is it like a "shared.yml" language file? I think otherwise it is possible to just skip all shared strings from sub-languages and only add them to your primary language
