### ISSUE TITLE
Incremental build doesn't pick up translation changes

### ISSUE THREAD

**Issue by Artanicus** [kurtsson/jekyll-multiple-languages-plugin#77]
Changing a translation file, e.g. _i18n/en.yml correctly triggers an incremental build but the build doesn't pick up the changed translation. No amount of translation changes will make it to the build until a full build is done.

The verbose log of the incremental build does display this:
"Loading translation from file /home/artanicus/project/_i18n/fi.yml"
But as far as I can see that updated data doesn't end up on the site.

**Comment by wouter-muller** [comment]
I have the same issue...

**Comment by kevinleguillou** [comment]
I created a pull-request for this (https://github.com/kurtsson/jekyll-multiple-languages-plugin/pull/141), the files are only loaded once on the PreRender hook.

You can clone my fork if you want in the meantime.

**Comment by shushugah** [comment]
This is now fixed, thanks to PR #141
